http:
  port: "8081"
  
file:
  accountsDir: "/Users/showlade/Desktop/APDevFundamentals4.3_studentFiles_SP_30oct2020/resources"
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"